name: Auto Tag + Release

on:
  workflow_call: {}

permissions:
  contents: write
  id-token: write

env:
  REGISTRY_PREFIX: us-central1-docker.pkg.dev/lytic-brew-mira-development/containers

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Auto-tag
        id: tagging
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Auth to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        # Remove project_id to avoid the config set command that's failing

      - name: Manually set project
        run: |
          echo "Setting project manually..."
          gcloud config set project lytic-brew-mira-development

      - name: Debug Authentication
        run: |
          echo "Current user:"
          gcloud auth list --filter=status:ACTIVE --format="value(account)"
          echo "Project config:"
          gcloud config list --format="value(core.project)"
          echo "Testing basic gcloud command:"
          gcloud projects describe lytic-brew-mira-development --format="value(projectId)"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ env.REGISTRY_PREFIX }}/${{ github.event.repository.name }}
        run: |
          echo "Building image: $IMAGE_NAME:${{ steps.tagging.outputs.new_tag }}"
          docker build -t $IMAGE_NAME:${{ steps.tagging.outputs.new_tag }} .
          echo "Pushing image: $IMAGE_NAME:${{ steps.tagging.outputs.new_tag }}"
          docker push $IMAGE_NAME:${{ steps.tagging.outputs.new_tag }}

      - name: Deploy to Cloud Run
        env:
          IMAGE_NAME: ${{ env.REGISTRY_PREFIX }}/${{ github.event.repository.name }}
        run: |
          gcloud run deploy journal-backend \
            --image=$IMAGE_NAME:${{ steps.tagging.outputs.new_tag }} \
            --region=us-central1 \
            --platform=managed \
            --service-account=journal-backend-sa@lytic-brew-mira-development.iam.gserviceaccount.com \
            --set-env-vars=GCP_PROJECT=lytic-brew-mira-development \
            --allow-unauthenticated