name: Docker Release Template

on:
  workflow_call:
    inputs:
      registry_prefix:
        required: true
        type: string  # e.g. us-central1-docker.pkg.dev/my-project/my-repo

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ inputs.registry_prefix }}

      - name: Build and Push Docker image
        env:
          REGISTRY_PREFIX: ${{ inputs.registry_prefix }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          IMAGE_NAME=\"$REGISTRY_PREFIX/$REPO_NAME\"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
